### PR TITLE
VCom AI Scripted Edition

### PR DESCRIPTION
**Pull request by davidcit646**
Add VCom AI, the scripted mod.

### CODE REVIEW

**Review by Jaidendude — COMMENTED** [review]
If we're adding the script version, are we also removing VCOM from the modset? We don't want this running twice.

I'm not sure if its already gone, though, so if it is, ignore me

**Review by Jaidendude — COMMENTED** [review]
Please link any relevant issues

**Comment by davidcit646** [comment]
Fuck this broken ass fuckin github bot that flags literally everything I do

**Review by davidcit646 — COMMENTED** [review]
The merge is going to result in error cause why wouldn't it.

**Pull request closed without merging**
