### PR TITLE
Fixing VCOM CBA Settings

### PR DESCRIPTION
**Pull request by Smiggus**
This pull request will:
- Amending the VCOM Ai CBA Setting

This pull request resolves the following issues:
- Screenshotted function

Notes:
Changed force force VCM_SIDEENABLED to be commented out

### CODE REVIEW

**Review by AndreasBrostrom — CHANGES_REQUESTED** [review]
one more setting using same format above as well

**Review by AndreasBrostrom — CHANGES_REQUESTED** [review]
https://github.com/7Cav/7Cav-Alive-Altis/blob/c999a082663e47a24359cd6dff64d6a42ca37083/cba_settings.sqf#L554

**Comment by Smiggus** [comment]
Added the ARTY Sides as well.

**Comment by Smiggus** [comment]
New Fix inbound for member already defined error in tac 2.

**Review by AndreasBrostrom — APPROVED** [review]
Looks great

**Review by davidcit646 — APPROVED** [review]

**Pull request merged**
