### PR TITLE
Cherno FIle

### PR DESCRIPTION
**Pull request by Smiggus**
This pull request will:
- Add Cherno to our map list

This pull request resloves the following issues:
Fixes #
N/A, first iteration
i.e.

Fixes #1
Addition of Chernarus mission.sqm file

Notes:
NEEDS SCRIPTS

### CODE REVIEW

**Comment by BojanOnTheInternet** [comment]
If this is to add Cherno, why are the two Altis maps included in the change?

**Comment by BojanOnTheInternet** [comment]
@davidcit646 are you intentionally removing the two Altis mission files entirely? Or were you trying to just remove them from the commit?

**Comment by davidcit646** [comment]
Just tried to remove them from the commit but I fucked it,

**Comment by davidcit646** [comment]
I included this in my branch already
https://github.com/7Cav/7Cav-Alive/pull/217

**Comment by davidcit646** [comment]
merged in #240

**Pull request closed without merging**
